/* GANTRY5 DEVELOPMENT MODE ENABLED.

   WARNING: This file is automatically generated by Gantry5. Any modifications to this file will be lost!

   For more information on modifying CSS, please read:

   http://docs.gantry.org/gantry5/configure/styles
   http://docs.gantry.org/gantry5/tutorials/adding-a-custom-style-sheet
 */

/* line 2, media/gantry5/engines/nucleus/scss/nucleus/mixins/_nav.scss */
/* line 12, media/gantry5/engines/nucleus/scss/nucleus/mixins/_nav.scss */
/* line 2, media/gantry5/engines/nucleus/scss/nucleus/mixins/_utilities.scss */
/* line 9, media/gantry5/engines/nucleus/scss/nucleus/mixins/_utilities.scss */
/* line 1, media/gantry5/engines/nucleus/scss/joomla/theme/_forms.scss */
legend {
  font-size: 1.3rem;
  line-height: 1.5;
}
/* line 6, media/gantry5/engines/nucleus/scss/joomla/theme/_forms.scss */
legend small {
  font-size: 0.8rem;
}
/* line 10, media/gantry5/engines/nucleus/scss/joomla/theme/_forms.scss */
.input-prepend > .add-on, .input-append > .add-on {
  line-height: 1.5;
}
@font-face {
  font-family: 'CrEAtoR cAmpoTYPe SmcP';
  font-style: normal;
  font-weight: normal;
  src: local('CrEAtoR cAmpoTYPe SmcP'), url('../../../../Creator_Campotype_smcp.woff') format('woff');
}
/* line 1, templates/it_medical/scss/medical-joomla/_core.scss */
.btn-group > .btn + .dropdown-toggle {
  box-shadow: 1px 1px 1px rgba(0, 0, 0, 0.1);
}
/* line 5, templates/it_medical/scss/medical-joomla/_core.scss */
.btn-group.open .btn-primary.dropdown-toggle {
  background: #303030;
  color: #fff;
  box-shadow: inset -1px -1px 1px rgba(0, 0, 0, 0.15);
}
/* line 11, templates/it_medical/scss/medical-joomla/_core.scss */
.dropdown-menu > li > a:hover, .dropdown-menu > li > a:focus, .dropdown-submenu:hover > a, .dropdown-submenu:focus > a {
  background-image: none;
  background-color: #3d3d3d;
}
/* line 16, templates/it_medical/scss/medical-joomla/_core.scss */
.btn-link {
  color: #3d3d3d;
}
/* line 21, templates/it_medical/scss/medical-joomla/_core.scss */
#login-form {
  margin-bottom: 0;
}
/* line 23, templates/it_medical/scss/medical-joomla/_core.scss */
#login-form #form-login-remember {
  margin: 20px 0 10px;
}
/* line 25, templates/it_medical/scss/medical-joomla/_core.scss */
#login-form #form-login-remember input {
  margin: 0 5px 0 0;
}
/* line 29, templates/it_medical/scss/medical-joomla/_core.scss */
#login-form ul.unstyled {
  margin: 20px 0 0;
}
/* line 31, templates/it_medical/scss/medical-joomla/_core.scss */
#login-form ul.unstyled a {
  color: #252d37;
}
/* line 33, templates/it_medical/scss/medical-joomla/_core.scss */
#login-form ul.unstyled a:hover {
  color: #3d3d3d;
}
/* line 36, templates/it_medical/scss/medical-joomla/_core.scss */
#login-form ul.unstyled a i {
  margin-right: 7px;
}
/* line 44, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 45, templates/it_medical/scss/medical-joomla/_core.scss */
.nav.menu {
  margin: 0;
}
/* line 47, templates/it_medical/scss/medical-joomla/_core.scss */
.nav.menu li {
  margin-bottom: 6.5px;
}
/* line 49, templates/it_medical/scss/medical-joomla/_core.scss */
.nav.menu li:last-child {
  margin-bottom: 0;
}
/* line 52, templates/it_medical/scss/medical-joomla/_core.scss */
.nav.menu li a {
  color: #252d37;
}
/* line 54, templates/it_medical/scss/medical-joomla/_core.scss */
.nav.menu li a:before {
  content: "\f105";
  font-family: FontAwesome;
  margin-right: 0.625rem;
}
/* line 59, templates/it_medical/scss/medical-joomla/_core.scss */
.nav.menu li a:hover {
  color: #3d3d3d;
}
/* line 63, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 64, templates/it_medical/scss/medical-joomla/_core.scss */
.nav.menu li span:before {
  content: "\f105";
  font-family: FontAwesome;
  margin-right: 0.625rem;
}
/* line 70, templates/it_medical/scss/medical-joomla/_core.scss */
.nav.menu li ul {
  margin-top: 6.5px;
  margin-bottom: 6.5px;
}
/* line 74, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 75, templates/it_medical/scss/medical-joomla/_core.scss */
.nav.menu li.current > a, .nav.menu li.current > span {
  color: #3d3d3d;
}
/* line 84, templates/it_medical/scss/medical-joomla/_core.scss */
.well {
  background: #f8f9fa;
  border: 1px solid #ecf0f1;
  box-shadow: none;
  padding: 30px 30px 10px;
}
/* line 92, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 93, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 94, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 95, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 96, templates/it_medical/scss/medical-joomla/_core.scss */
.login > form fieldset .control-group .control-label {
  text-align: left;
  padding-top: 10px;
}
/* line 100, templates/it_medical/scss/medical-joomla/_core.scss */
.login > form fieldset .control-group #remember {
  margin-top: 10px;
}
@media only all and (max-width: 47.938rem) {
  .login > form fieldset .control-group #remember {
    width: auto;
  }
}
/* line 106, templates/it_medical/scss/medical-joomla/_core.scss */
@media only all and (max-width: 47.938rem) {
  .login > form fieldset .control-group input {
    width: 100%;
  }
}
/* line 116, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 117, templates/it_medical/scss/medical-joomla/_core.scss */
.logout .controls {
  margin-left: 0;
}
/* line 122, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 123, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 124, templates/it_medical/scss/medical-joomla/_core.scss */
ul.nav-tabs.nav-stacked > li > a {
  border: 1px solid #ecf0f1;
}
/* line 126, templates/it_medical/scss/medical-joomla/_core.scss */
ul.nav-tabs.nav-stacked > li > a:hover {
  border: 1px solid #ecf0f1;
}
/* line 134, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 135, templates/it_medical/scss/medical-joomla/_core.scss */
.registration #member-registration {
  margin-bottom: 0;
}
/* line 137, templates/it_medical/scss/medical-joomla/_core.scss */
.registration #member-registration legend + .control-group {
  margin-top: 0;
}
/* line 140, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 141, templates/it_medical/scss/medical-joomla/_core.scss */
.registration #member-registration .control-group .control-label {
  text-align: left;
  padding-top: 10px;
}
/* line 145, templates/it_medical/scss/medical-joomla/_core.scss */
@media only all and (max-width: 47.938rem) {
  .registration #member-registration .control-group input {
    width: 100%;
  }
}
/* line 155, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 156, templates/it_medical/scss/medical-joomla/_core.scss */
.remind #user-registration, .reset #user-registration {
  margin-bottom: 0;
}
/* line 158, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 159, templates/it_medical/scss/medical-joomla/_core.scss */
.remind #user-registration fieldset p, .reset #user-registration fieldset p {
  margin-top: 0;
}
/* line 163, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 164, templates/it_medical/scss/medical-joomla/_core.scss */
.remind #user-registration .control-group .control-label, .reset #user-registration .control-group .control-label {
  text-align: left;
  padding-top: 10px;
}
/* line 173, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 174, templates/it_medical/scss/medical-joomla/_core.scss */
.profile > ul.btn-toolbar {
  margin-top: 0;
}
/* line 177, templates/it_medical/scss/medical-joomla/_core.scss */
.profile #users-profile-core {
  margin-bottom: 20px;
}
/* line 180, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 181, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 182, templates/it_medical/scss/medical-joomla/_core.scss */
.profile fieldset dl dt {
  text-align: left;
}
/* line 190, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 191, templates/it_medical/scss/medical-joomla/_core.scss */
.profile-edit #member-profile {
  margin-bottom: 0;
}
/* line 193, templates/it_medical/scss/medical-joomla/_core.scss */
/* line 194, templates/it_medical/scss/medical-joomla/_core.scss */
.profile-edit #member-profile .control-group .control-label {
  text-align: left;
  padding-top: 10px;
}
/* line 198, templates/it_medical/scss/medical-joomla/_core.scss */
.profile-edit #member-profile .control-group .chzn-container {
  padding-top: 8px;
}
/* line 2, templates/it_medical/scss/medical-joomla/_typography.scss */
.list-striped, .row-striped {
  border-top: 1px solid #ecf0f1;
}
/* line 7, templates/it_medical/scss/medical-joomla/_typography.scss */
.list-striped li, .list-striped dd, .row-striped .row, .row-striped .row-fluid {
  border-bottom: 1px solid #ecf0f1;
}
/* line 14, templates/it_medical/scss/medical-joomla/_typography.scss */
.list-striped li:nth-child(odd), .list-striped dd:nth-child(odd), .row-striped .row:nth-child(odd), .row-striped .row-fluid:nth-child(odd) {
  background-color: #fcfcfc;
}
/* line 21, templates/it_medical/scss/medical-joomla/_typography.scss */
.list-striped li:hover, .list-striped dd:hover, .row-striped .row:hover, .row-striped .row-fluid:hover {
  background-color: #f2f2f2;
}
/* line 28, templates/it_medical/scss/medical-joomla/_typography.scss */
.list-bordered, .row-bordered {
  border: 1px solid #ecf0f1;
}
/* line 33, templates/it_medical/scss/medical-joomla/_typography.scss */
.row-even, .row-odd {
  border-bottom: 1px solid #ecf0f1;
}
/* line 38, templates/it_medical/scss/medical-joomla/_typography.scss */
.row-even {
  background-color: #fcfcfc;
}
/* line 42, templates/it_medical/scss/medical-joomla/_typography.scss */
.iframe-bordered {
  border: 1px solid #ecf0f1;
}
/* line 47, templates/it_medical/scss/medical-joomla/_typography.scss */
blockquote {
  border-left: 5px solid #ecf0f1;
}
/* line 52, templates/it_medical/scss/medical-joomla/_typography.scss */
blockquote small {
  color: #aaa;
}
/* line 56, templates/it_medical/scss/medical-joomla/_typography.scss */
blockquote.pull-right {
  border-right: 5px solid #ecf0f1;
}
/* line 1, templates/it_medical/scss/medical-joomla/_forms.scss */
legend {
  color: #333;
}
/* line 5, templates/it_medical/scss/medical-joomla/_forms.scss */
legend small {
  color: #999;
}
/* line 9, templates/it_medical/scss/medical-joomla/_forms.scss */
.input-prepend .chzn-container-single .chzn-single, .input-append .chzn-container-single .chzn-single {
  border-color: #ecf0f1;
}
/* line 14, templates/it_medical/scss/medical-joomla/_forms.scss */
.input-prepend .chzn-container-single .chzn-drop, .input-append .chzn-container-single .chzn-drop {
  border-color: #ecf0f1;
}
/* line 19, templates/it_medical/scss/medical-joomla/_forms.scss */
textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"], .uneditable-input {
  background-color: #fff;
  border: 1px solid #e3e9eb;
  box-shadow: none;
  padding: 10px;
  border-radius: 0;
  -webkit-transition: border 0.2s linear, box-shadow 0.2s linear;
  -moz-transition: border 0.2s linear, box-shadow 0.2s linear;
  transition: border 0.2s linear, box-shadow 0.2s linear;
}
/* line 41, templates/it_medical/scss/medical-joomla/_forms.scss */
textarea:focus, input[type="text"]:focus, input[type="password"]:focus, input[type="datetime"]:focus, input[type="datetime-local"]:focus, input[type="date"]:focus, input[type="month"]:focus, input[type="time"]:focus, input[type="week"]:focus, input[type="number"]:focus, input[type="email"]:focus, input[type="url"]:focus, input[type="search"]:focus, input[type="tel"]:focus, input[type="color"]:focus, .uneditable-input:focus {
  box-shadow: none;
}
/* line 46, templates/it_medical/scss/medical-joomla/_forms.scss */
/* line 47, templates/it_medical/scss/medical-joomla/_forms.scss */
#g-aside input, #g-sidebar input, #g-offcanvas input, #g-aside textarea, #g-sidebar textarea, #g-offcanvas textarea, #g-aside .uneditable-input, #g-sidebar .uneditable-input, #g-offcanvas .uneditable-input {
  width: 100%;
}
/* line 50, templates/it_medical/scss/medical-joomla/_forms.scss */
#g-aside input[type="file"], #g-sidebar input[type="file"], #g-offcanvas input[type="file"], #g-aside input[type="image"], #g-sidebar input[type="image"], #g-offcanvas input[type="image"], #g-aside input[type="submit"], #g-sidebar input[type="submit"], #g-offcanvas input[type="submit"], #g-aside input[type="reset"], #g-sidebar input[type="reset"], #g-offcanvas input[type="reset"], #g-aside input[type="button"], #g-sidebar input[type="button"], #g-offcanvas input[type="button"], #g-aside input[type="radio"], #g-sidebar input[type="radio"], #g-offcanvas input[type="radio"], #g-aside input[type="checkbox"], #g-sidebar input[type="checkbox"], #g-offcanvas input[type="checkbox"] {
  width: auto;
}
/* line 55, templates/it_medical/scss/medical-joomla/_forms.scss */
/* line 56, templates/it_medical/scss/medical-joomla/_forms.scss */
/* line 57, templates/it_medical/scss/medical-joomla/_forms.scss */
#g-header .search form, #g-navigation .search form {
  margin-bottom: 0;
}
/* line 60, templates/it_medical/scss/medical-joomla/_forms.scss */
#g-header .search input, #g-navigation .search input {
  margin-bottom: 0;
  border: 0;
}
/* line 68, templates/it_medical/scss/medical-joomla/_forms.scss */
/* line 69, templates/it_medical/scss/medical-joomla/_forms.scss */
.view-mailto #g-page-surround, .body-only #g-page-surround {
  box-shadow: none;
}
/* line 1, templates/it_medical/scss/medical-joomla/_tabs.scss */
.nav-tabs.nav-dark {
  border-bottom: 1px solid #333;
  text-shadow: 1px 1px 1px #000;
}
/* line 6, templates/it_medical/scss/medical-joomla/_tabs.scss */
.nav-tabs.nav-dark > li > a {
  color: #f8f8f8;
}
/* line 10, templates/it_medical/scss/medical-joomla/_tabs.scss */
.nav-tabs.nav-dark > li > a:hover {
  border-color: #333 #333 #111;
  background-color: #777;
}
/* line 15, templates/it_medical/scss/medical-joomla/_tabs.scss */
.nav-tabs.nav-dark > .active > a, .nav-tabs.nav-dark > .active > a:hover {
  color: #fff;
  background-color: #555;
  border: 1px solid #222;
}
/* line 3, templates/it_medical/scss/medical-joomla/_utilities.scss */
.tip-wrap {
  color: #fff;
  background-color: #000;
}
/* line 9, templates/it_medical/scss/medical-joomla/_utilities.scss */
.search span.highlight {
  background-color: #fcfcfc;
}
/* line 14, templates/it_medical/scss/medical-joomla/_utilities.scss */
.img-polaroid {
  background-color: #fff;
  border: 1px solid rgba(0, 0, 0, 0.2);
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}
/* line 21, templates/it_medical/scss/medical-joomla/_utilities.scss */
.muted {
  color: #999;
}
/* line 25, templates/it_medical/scss/medical-joomla/_utilities.scss */
a.muted:hover, a.muted:focus {
  color: #808080;
}
/* line 30, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert {
  background-color: #f8f4ec;
  border-color: #eee4d2;
}
/* line 34, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert a, .alert a:hover, .alert .alert-link, .alert .alert-link:hover {
  color: #a47e3c;
  font-weight: bold;
}
/* line 38, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert a:hover, .alert a:hover:hover, .alert .alert-link:hover, .alert .alert-link:hover:hover {
  text-decoration: underline;
}
/* line 44, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert, .text-warning {
  color: #c09853;
}
/* line 49, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert h4 {
  color: #c09853 !important;
}
/* line 53, templates/it_medical/scss/medical-joomla/_utilities.scss */
a.text-warning:hover, a.text-warning:focus {
  color: #b78c43;
}
/* line 58, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-success {
  color: #468847;
  background-color: #dfeedf;
  border-color: #c4e0c4;
}
/* line 63, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-success a, .alert-success a:hover, .alert-success .alert-link, .alert-success .alert-link:hover {
  color: #356635;
  font-weight: bold;
}
/* line 67, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-success a:hover, .alert-success a:hover:hover, .alert-success .alert-link:hover, .alert-success .alert-link:hover:hover {
  text-decoration: underline;
}
/* line 73, templates/it_medical/scss/medical-joomla/_utilities.scss */
.text-success {
  color: #468847;
}
/* line 77, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-success h4 {
  color: #468847 !important;
}
/* line 81, templates/it_medical/scss/medical-joomla/_utilities.scss */
a.text-success:hover, a.text-success:focus {
  color: #3d773e;
}
/* line 86, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-danger, .alert-error {
  color: #b94a48;
  background-color: #f6e7e7;
  border-color: #edd1d0;
}
/* line 92, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-danger a, .alert-error a, .alert-danger a:hover, .alert-error a:hover, .alert-danger .alert-link, .alert-error .alert-link, .alert-danger .alert-link:hover, .alert-error .alert-link:hover {
  color: #953b39;
  font-weight: bold;
}
/* line 96, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-danger a:hover, .alert-error a:hover, .alert-danger a:hover:hover, .alert-error a:hover:hover, .alert-danger .alert-link:hover, .alert-error .alert-link:hover, .alert-danger .alert-link:hover:hover, .alert-error .alert-link:hover:hover {
  text-decoration: underline;
}
/* line 102, templates/it_medical/scss/medical-joomla/_utilities.scss */
.text-error {
  color: #b94a48;
}
/* line 106, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-danger h4, .alert-error h4 {
  color: #b94a48 !important;
}
/* line 111, templates/it_medical/scss/medical-joomla/_utilities.scss */
a.text-error:hover, a.text-error:focus {
  color: #a74240;
}
/* line 116, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-info {
  color: #3a87ad;
  background-color: #e2eff5;
  border-color: #c7e0ec;
}
/* line 121, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-info a, .alert-info a:hover, .alert-info .alert-link, .alert-info .alert-link:hover {
  color: #2d6987;
  font-weight: bold;
}
/* line 125, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-info a:hover, .alert-info a:hover:hover, .alert-info .alert-link:hover, .alert-info .alert-link:hover:hover {
  text-decoration: underline;
}
/* line 131, templates/it_medical/scss/medical-joomla/_utilities.scss */
.text-info {
  color: #3a87ad;
}
/* line 135, templates/it_medical/scss/medical-joomla/_utilities.scss */
.alert-info h4 {
  color: #3a87ad !important;
}
/* line 139, templates/it_medical/scss/medical-joomla/_utilities.scss */
a.text-info:hover, a.text-info:focus {
  color: #34789a;
}
/* line 145, templates/it_medical/scss/medical-joomla/_utilities.scss */
.platform-content input {
  box-sizing: inherit;
}
/* line 150, templates/it_medical/scss/medical-joomla/_utilities.scss */
.form-actions {
  background-color: transparent;
  border: none;
  margin: 0;
  padding: 0;
}
/* line 158, templates/it_medical/scss/medical-joomla/_utilities.scss */
.element-invisible {
  border: 0 none;
  height: 1px;
  margin: 0;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}
/* line 1, templates/it_medical/scss/medical-joomla/_contacts.scss */
/* line 2, templates/it_medical/scss/medical-joomla/_contacts.scss */
.contact > h3 {
  display: none;
}
/* line 5, templates/it_medical/scss/medical-joomla/_contacts.scss */
.contact .contact-address {
  margin: 0;
}
/* line 8, templates/it_medical/scss/medical-joomla/_contacts.scss */
.contact #contact-form {
  margin-bottom: 0;
}
/* line 10, templates/it_medical/scss/medical-joomla/_contacts.scss */
/* line 11, templates/it_medical/scss/medical-joomla/_contacts.scss */
.contact #contact-form fieldset > legend {
  font-size: 1.15rem;
  color: #9e9e9e;
  margin-bottom: 0;
}
/* line 17, templates/it_medical/scss/medical-joomla/_contacts.scss */
/* line 18, templates/it_medical/scss/medical-joomla/_contacts.scss */
.contact #contact-form.form-horizontal .control-label {
  text-align: left;
}
/* line 22, templates/it_medical/scss/medical-joomla/_contacts.scss */
.contact #contact-form input, .contact #contact-form textarea {
  width: 300px;
}
@media only all and (max-width: 47.938rem) {
  .contact #contact-form input, .contact #contact-form textarea {
    width: 100%;
  }
}
@media only all and (min-width: 48rem) and (max-width: 59.938rem) {
  .contact #contact-form input, .contact #contact-form textarea {
    width: 100%;
  }
}
/* line 31, templates/it_medical/scss/medical-joomla/_contacts.scss */
.contact #contact-form #jform_contact_email_copy {
  width: 10px;
}
/* line 34, templates/it_medical/scss/medical-joomla/_contacts.scss */
.contact #contact-form label {
  margin-top: 3px;
}
/* line 37, templates/it_medical/scss/medical-joomla/_contacts.scss */
.contact #contact-form #jform_contact_email_copy-lbl {
  margin-top: 0;
}
/* line 40, templates/it_medical/scss/medical-joomla/_contacts.scss */
@media only all and (max-width: 47.938rem) {
  .contact #contact-form .form-actions {
    padding: 0;
  }
  /* line 43, templates/it_medical/scss/medical-joomla/_contacts.scss */
  .contact #contact-form .form-actions > button {
    display: block;
    width: 100%;
  }
}
/* line 49, templates/it_medical/scss/medical-joomla/_contacts.scss */
.contact #contact-form.well {
  border: none;
  padding: 0;
  background: none;
}
/* line 1, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
ul.breadcrumb {
  margin: 6px 0 0;
  padding: 0;
  background: none;
}
@media only all and (max-width: 47.938rem) {
  ul.breadcrumb {
    margin: 0;
  }
}
/* line 8, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
ul.breadcrumb li {
  text-shadow: none;
}
/* line 10, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
ul.breadcrumb li .divider {
  display: none;
}
/* line 13, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
/* line 14, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
ul.breadcrumb li + li:after {
  content: "/ ";
  padding: 0 5px;
}
/* line 18, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
/* line 19, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
ul.breadcrumb li + li:last-child:after {
  content: none;
  padding: 0;
}
/* line 28, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
/* line 29, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
/* line 30, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
/* line 31, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
.g-grid > .g-block:last-child ul.breadcrumb {
  text-align: right;
}
@media only all and (max-width: 47.938rem) {
  .g-grid > .g-block:last-child ul.breadcrumb {
    text-align: center;
  }
}
/* line 38, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
/* line 39, templates/it_medical/scss/medical-joomla/_breadcrumb.scss */
.g-grid > .g-block:first-child ul.breadcrumb {
  text-align: left;
}
@media only all and (max-width: 47.938rem) {
  .g-grid > .g-block:first-child ul.breadcrumb {
    text-align: center;
  }
}
/* line 1, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 2, templates/it_medical/scss/medical-joomla/_blog.scss */
.blog .category-desc, .blog-featured .category-desc {
  margin: -10px 0 30px;
}
/* line 6, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 7, templates/it_medical/scss/medical-joomla/_blog.scss */
.blog .items-more ol, .blog-featured .items-more ol {
  padding-left: 0;
  margin: 0 0 60px 0;
}
/* line 12, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 13, templates/it_medical/scss/medical-joomla/_blog.scss */
.blog article.item, .blog-featured article.item {
  margin-bottom: 60px;
}
/* line 19, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 20, templates/it_medical/scss/medical-joomla/_blog.scss */
.item-page ul.pager {
  margin-bottom: 0;
}
/* line 25, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 26, templates/it_medical/scss/medical-joomla/_blog.scss */
article .item-image {
  margin-bottom: 20px;
}
/* line 31, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 32, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 33, templates/it_medical/scss/medical-joomla/_blog.scss */
.tag-category li h3 {
  margin: 10px 0;
}
/* line 35, templates/it_medical/scss/medical-joomla/_blog.scss */
.tag-category li h3 a {
  color: #252d37;
}
/* line 37, templates/it_medical/scss/medical-joomla/_blog.scss */
.tag-category li h3 a:hover {
  color: #3d3d3d;
}
/* line 43, templates/it_medical/scss/medical-joomla/_blog.scss */
.tag-category form {
  margin-bottom: 0;
}
/* line 48, templates/it_medical/scss/medical-joomla/_blog.scss */
.g-article-header {
  padding: 0 0 25px 0;
  border-bottom: 1px solid #ecf0f1;
}
/* line 51, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 52, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 53, templates/it_medical/scss/medical-joomla/_blog.scss */
.g-article-header > .icons .btn-group .btn {
  padding: 0.3rem 0.6rem !important;
}
/* line 55, templates/it_medical/scss/medical-joomla/_blog.scss */
.g-article-header > .icons .btn-group .btn .caret {
  border-top-color: #777;
  margin-left: 3px;
  -webkit-transition: all 0.2s;
  -moz-transition: all 0.2s;
  transition: all 0.2s;
}
/* line 60, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 61, templates/it_medical/scss/medical-joomla/_blog.scss */
.g-article-header > .icons .btn-group .btn:hover .caret, .g-article-header > .icons .btn-group .btn:focus .caret {
  border-top-color: #fff;
}
/* line 68, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 69, templates/it_medical/scss/medical-joomla/_blog.scss */
.g-article-header .page-header h2 {
  margin: 0 0 -10px 0;
}
/* line 71, templates/it_medical/scss/medical-joomla/_blog.scss */
.g-article-header .page-header h2 a {
  color: #252d37;
}
/* line 73, templates/it_medical/scss/medical-joomla/_blog.scss */
.g-article-header .page-header h2 a:hover {
  color: #3d3d3d;
}
/* line 81, templates/it_medical/scss/medical-joomla/_blog.scss */
.readmore {
  margin: 0;
}
/* line 83, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 84, templates/it_medical/scss/medical-joomla/_blog.scss */
.readmore .btn span {
  display: none;
}
/* line 90, templates/it_medical/scss/medical-joomla/_blog.scss */
.tags {
  margin-bottom: 1.5rem;
}
/* line 94, templates/it_medical/scss/medical-joomla/_blog.scss */
.article-info {
  margin: 20px 0 0;
}
/* line 96, templates/it_medical/scss/medical-joomla/_blog.scss */
.article-info .article-info-term {
  display: none;
}
/* line 99, templates/it_medical/scss/medical-joomla/_blog.scss */
.article-info dd {
  display: inline-block;
  margin: 0 20px 0 0;
}
/* line 102, templates/it_medical/scss/medical-joomla/_blog.scss */
.article-info dd i {
  margin-right: 5px;
}
/* line 108, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 109, templates/it_medical/scss/medical-joomla/_blog.scss */
.content-category form {
  margin-bottom: 0;
}
/* line 112, templates/it_medical/scss/medical-joomla/_blog.scss */
.content-category .pagination {
  margin-bottom: 0;
}
/* line 114, templates/it_medical/scss/medical-joomla/_blog.scss */
.content-category .pagination > ul {
  margin-bottom: 0;
  box-shadow: none;
}
/* line 118, templates/it_medical/scss/medical-joomla/_blog.scss */
.content-category .pagination .counter {
  margin-bottom: 0;
}
@media only all and (max-width: 47.938rem) {
  .content-category .pagination .counter {
    float: none;
  }
}
/* line 127, templates/it_medical/scss/medical-joomla/_blog.scss */
.pagination {
  margin: 0;
}
/* line 129, templates/it_medical/scss/medical-joomla/_blog.scss */
.pagination ul {
  margin: 0;
  box-shadow: none;
}
/* line 132, templates/it_medical/scss/medical-joomla/_blog.scss */
/* line 133, templates/it_medical/scss/medical-joomla/_blog.scss */
.pagination ul > li > a, .pagination ul > li > span {
  color: #777;
  padding: 6px 15px;
  margin-right: 5px;
  border: 1px solid #ecf0f1;
  -webkit-transition: background 0.2s;
  -moz-transition: background 0.2s;
  transition: background 0.2s;
}
/* line 142, templates/it_medical/scss/medical-joomla/_blog.scss */
.pagination .counter {
  margin: 7px 0 0;
}
@media only all and (max-width: 47.938rem) {
  .pagination .counter {
    float: none;
  }
}
/* line 1, templates/it_medical/scss/medical-joomla/_revolution.scss */
/* line 2, templates/it_medical/scss/medical-joomla/_revolution.scss */
/* line 3, templates/it_medical/scss/medical-joomla/_revolution.scss */
/* line 4, templates/it_medical/scss/medical-joomla/_revolution.scss */
.rev_slider_wrapper .tp-caption a.button {
  color: #fff;
}
/* line 6, templates/it_medical/scss/medical-joomla/_revolution.scss */
.rev_slider_wrapper .tp-caption a.button.dark {
  margin-left: 10px;
}
/* line 13, templates/it_medical/scss/medical-joomla/_revolution.scss */
.rev_slider_wrapper .tparrows:before {
  color: #fff;
  display: inline-block;
  font-family: FontAwesome, sans-serif;
  font-size: 20px;
  font-style: normal;
  font-weight: bold;
  margin-right: 0;
  margin-top: 2px;
  text-align: center;
  text-decoration: inherit;
  width: 35px;
}
/* line 26, templates/it_medical/scss/medical-joomla/_revolution.scss */
.rev_slider_wrapper .tparrows {
  background: #000;
  background: none repeat scroll 0 0 rgba(0, 0, 0, 0.4);
  border-radius: 5px;
  cursor: pointer;
  height: 35px;
  width: 35px;
  -webkit-transition: background 0.3s, opacity 0.3s;
  -moz-transition: background 0.3s, opacity 0.3s;
  transition: background 0.3s, opacity 0.3s;
}
/* line 35, templates/it_medical/scss/medical-joomla/_revolution.scss */
.rev_slider_wrapper .tparrows:hover {
  color: #fff;
}
/* line 38, templates/it_medical/scss/medical-joomla/_revolution.scss */
.rev_slider_wrapper .tp-leftarrow:before {
  content: "\f104";
}
/* line 41, templates/it_medical/scss/medical-joomla/_revolution.scss */
.rev_slider_wrapper .tp-rightarrow:before {
  content: "\f105";
}
/* line 44, templates/it_medical/scss/medical-joomla/_revolution.scss */
.rev_slider_wrapper .tparrows.tp-rightarrow:before {
  margin-left: 1px;
}
/* line 47, templates/it_medical/scss/medical-joomla/_revolution.scss */
.rev_slider_wrapper .tparrows:hover {
  background: #000;
}
/* line 1, templates/it_medical/scss/medical-joomla/_nssp2.scss */
/* line 2, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-title {
  margin: 0 0 10px;
  font-size: 1.15rem;
  font-weight: normal;
}
/* line 6, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-title a {
  color: #252d37;
}
/* line 8, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-title a:hover {
  color: #3d3d3d;
}
/* line 13, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-introtext {
  margin: 0;
}
/* line 16, templates/it_medical/scss/medical-joomla/_nssp2.scss */
/* line 17, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-social span {
  margin-left: 0 !important;
  margin-right: 10px;
}
/* line 22, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-rating {
  margin-bottom: 10px;
}
/* line 25, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links {
  margin-top: 10px;
  font-size: 0.9rem;
}
/* line 28, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-created {
  margin-right: 15px;
}
/* line 30, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-created:before {
  content: "\f017";
  font-family: FontAwesome;
  margin-right: 2px;
}
/* line 36, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-author {
  margin-right: 15px;
}
/* line 38, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-author:before {
  content: "\f007";
  font-family: FontAwesome;
  margin-right: 2px;
}
/* line 44, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-category {
  margin-right: 15px;
}
/* line 46, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-category a {
  color: #777;
}
/* line 48, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-category a:before {
  content: "\f07c";
  font-family: FontAwesome;
  margin-right: 2px;
}
/* line 53, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-category a:hover {
  color: #3d3d3d;
}
/* line 58, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-comments {
  margin: 0;
  margin-right: 15px;
  color: #777;
  background: none;
  padding: 0;
  font-size: inherit;
}
/* line 65, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-comments:before {
  content: "\f086";
  font-family: FontAwesome;
  margin-right: 6px;
}
/* line 70, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-comments:hover {
  color: #3d3d3d;
}
/* line 74, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-hits {
  margin-right: 15px;
  background: none;
  padding: 0;
  color: #777;
  font-size: inherit;
}
/* line 80, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-hits:before {
  content: "\f06e";
  font-family: FontAwesome;
  margin-right: 6px;
}
/* line 86, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-readmore {
  margin: 0;
  margin-right: 15px;
  color: #777;
}
/* line 90, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-readmore span {
  background: none;
  padding: 0;
  font-size: inherit;
}
/* line 95, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-readmore:before {
  content: "\f0c1";
  font-family: FontAwesome;
  margin-right: 6px;
}
/* line 100, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-links .ns2-readmore:hover {
  color: #3d3d3d;
}
/* line 105, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-page-inner-custom {
  overflow: hidden;
}
/* line 107, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-page-inner-custom > div {
  margin-bottom: 30px;
}
/* line 109, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-page-inner-custom > div:last-child {
  margin-bottom: 0;
}
/* line 114, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-image-link {
  position: relative;
}
/* line 116, templates/it_medical/scss/medical-joomla/_nssp2.scss */
/* line 117, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-image-link:hover .ns2-image-overlay {
  opacity: 1;
}
@media only all and (max-width: 30rem) {
  .nssp2 .ns2-image-link {
    margin-bottom: 15px;
  }
}
/* line 125, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-image-overlay {
  background: rgba(0, 0, 0, 0.5);
  color: #fff;
  padding: 20px;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  opacity: 0;
  -webkit-transition: opacity 0.3s;
  -moz-transition: opacity 0.3s;
  transition: opacity 0.3s;
}
/* line 136, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-image-overlay:before {
  font-size: 25px;
  height: 25px;
  width: 25px;
  margin-left: -11px;
  margin-top: -17px;
  color: #fff;
  position: absolute;
  left: 50%;
  top: 50%;
  content: "\f0c1";
  font-family: FontAwesome;
}
/* line 151, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-wrap {
  position: relative;
}
/* line 153, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-wrap .ns2-art-controllers {
  position: absolute;
  top: -58px;
  right: 0;
}
/* line 157, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-prev, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-prev, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-play, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-play, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-pause, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-pause, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-next, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-next, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-pagination span, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-pagination span {
  background: none;
  text-indent: 0;
  height: auto;
  width: auto;
}
/* line 163, templates/it_medical/scss/medical-joomla/_nssp2.scss */
/* line 164, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-pagination span, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-pagination span {
  color: #777;
  -webkit-transition: color 0.2s;
  -moz-transition: color 0.2s;
  transition: color 0.2s;
}
/* line 167, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-pagination span:hover, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-pagination span:hover, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-pagination span.active, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-pagination span.active {
  color: #aaa;
}
/* line 172, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-prev, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-prev, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-next, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-next {
  padding: 5px 10px;
  background: #3d3d3d;
  color: #fff;
  border-radius: 3px;
  font-size: 11px;
  margin-top: -4px;
  margin-right: 0;
  margin-left: 5px;
  -webkit-transition: all 0.2s;
  -moz-transition: all 0.2s;
  transition: all 0.2s;
}
/* line 182, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-prev i, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-prev i, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-next i, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-next i {
  vertical-align: middle;
}
/* line 185, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-prev:hover, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-prev:hover, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-art-next:hover, .nssp2 .ns2-wrap .ns2-art-controllers .ns2-links-next:hover {
  background: #252d37;
}
/* line 193, templates/it_medical/scss/medical-joomla/_nssp2.scss */
/* line 194, templates/it_medical/scss/medical-joomla/_nssp2.scss */
/* line 195, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.footer .nssp2 .ns2-title {
  font-size: 1rem;
  margin: 0;
}
/* line 200, templates/it_medical/scss/medical-joomla/_nssp2.scss */
/* line 201, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.footer .ns2-page-inner-custom > div {
  margin: 0;
  border-bottom: 1px solid #0d0d0d;
}
/* line 204, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.footer .ns2-page-inner-custom > div:last-child {
  border: none;
}
/* line 206, templates/it_medical/scss/medical-joomla/_nssp2.scss */
/* line 207, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.footer .ns2-page-inner-custom > div:last-child .ns2-column > div {
  padding-bottom: 0 !important;
}
/* line 213, templates/it_medical/scss/medical-joomla/_nssp2.scss */
/* line 214, templates/it_medical/scss/medical-joomla/_nssp2.scss */
/* line 215, templates/it_medical/scss/medical-joomla/_nssp2.scss */
.footer .ns2-page-inner-custom .ns2-first .ns2-column > div {
  padding-top: 0 !important;
}
/* line 2, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 3, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-title {
  background: url('../../images/listclosed.png') no-repeat scroll 98% #f8f9fa;
  border: none;
  border-bottom: 1px solid #ecf0f1;
  border-radius: 0;
  margin: 0 !important;
  font-size: 1.15rem !important;
  line-height: inherit !important;
  padding: 13px 15px !important;
  -webkit-transition: color 0.2s;
  -moz-transition: color 0.2s;
  transition: color 0.2s;
}
/* line 13, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-title:hover {
  color: #3d3d3d !important;
}
/* line 16, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-title .indicator {
  display: none;
}
/* line 20, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 21, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 22, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists li.active .sprocket-lists-title {
  background: url('../../images/listopen.png') no-repeat scroll 98% #f8f9fa;
}
/* line 27, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 28, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-item .sprocket-padding {
  padding: 18px 15px;
}
/* line 31, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 32, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-item .readon:hover {
  color: #3d3d3d;
  text-decoration: underline;
}
/* line 38, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-nav {
  position: absolute;
  top: -58px;
  right: 0;
  width: auto;
  padding: 0;
}
/* line 44, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-nav .sprocket-lists-pagination {
  margin: 0 10px;
  display: block;
}
/* line 47, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-nav .sprocket-lists-pagination li {
  background: none;
  color: #777;
  box-shadow: none;
  padding: 0 !important;
  opacity: 1;
  -webkit-transition: color 0.2s;
  -moz-transition: color 0.2s;
  transition: color 0.2s;
}
/* line 54, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-nav .sprocket-lists-pagination li:hover, .sprocket-lists .sprocket-lists-nav .sprocket-lists-pagination li.active {
  color: #aaa;
}
/* line 59, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 60, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-nav .sprocket-lists-arrows .arrow {
  background: #3d3d3d;
  box-shadow: none;
  padding: 5px 10px;
  font-size: 11px;
  border-radius: 3px;
  color: #fff;
  margin-left: 5px;
  margin-right: 0;
  margin-top: -4px;
  width: auto;
  height: auto;
  opacity: 1;
  -webkit-transition: all 0.2s;
  -moz-transition: all 0.2s;
  transition: all 0.2s;
}
/* line 74, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-nav .sprocket-lists-arrows .arrow i {
  vertical-align: middle;
}
/* line 77, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-nav .sprocket-lists-arrows .arrow:hover {
  background: #252d37;
}
/* line 82, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-lists .sprocket-lists-nav .spinner {
  margin-top: 2px;
}
/* line 88, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 89, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 90, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.white .sprocket-lists .sprocket-lists-title {
  background: url('../../images/listclosed.png') no-repeat scroll 98% #fff;
}
/* line 94, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 95, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 96, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.white li.active .sprocket-lists-title {
  background: url('../../images/listopen.png') no-repeat scroll 98% #fff;
}
/* line 104, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 105, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 106, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-features.layout-slideshow .sprocket-features-content {
  bottom: 40px;
  top: auto;
  width: 60%;
}
/* line 110, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 111, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-features.layout-slideshow .sprocket-features-content .readon:hover {
  color: #3d3d3d;
  text-decoration: underline;
}
@media only all and (max-width: 47.938rem) {
  .sprocket-features.layout-slideshow .sprocket-features-content {
    bottom: 0;
    left: 0;
    width: 100%;
  }
}
@media only all and (min-width: 48rem) and (max-width: 59.938rem) {
  .sprocket-features.layout-slideshow .sprocket-features-content {
    bottom: 0;
    left: 0;
    width: 100%;
  }
}
/* line 126, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
@media only all and (max-width: 47.938rem) {
  .sprocket-features.layout-slideshow .sprocket-features-content .sprocket-features-desc {
    display: none;
  }
}
/* line 132, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-features.layout-slideshow .sprocket-features-pagination {
  top: 15px;
  right: 20px;
  bottom: auto;
  left: auto;
}
/* line 138, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 139, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-features.layout-slideshow .sprocket-features-arrows .arrow {
  font-size: 1.4rem;
  line-height: 1.4rem;
}
/* line 144, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-features.layout-slideshow .sprocket-features-title {
  font-size: 1.5rem;
  color: #fff !important;
}
@media only all and (max-width: 47.938rem) {
  .sprocket-features.layout-slideshow .sprocket-features-title {
    font-size: 1rem;
    margin: 0;
    display: block;
  }
}
/* line 157, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 158, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 159, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs.layout-top .sprocket-tabs-nav {
  border-bottom: 1px solid #ecf0f1;
  margin-bottom: 20px;
}
/* line 163, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs.layout-top li {
  border-right: 1px solid #ecf0f1 !important;
}
/* line 167, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 168, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs.layout-left .sprocket-tabs-nav {
  border-right: 1px solid #ecf0f1;
}
/* line 171, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs.layout-left li {
  border-bottom: 1px solid #ecf0f1 !important;
}
/* line 175, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 176, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs.layout-right .sprocket-tabs-nav {
  border-left: 1px solid #ecf0f1;
}
/* line 179, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs.layout-right li {
  border-bottom: 1px solid #ecf0f1 !important;
}
/* line 183, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 184, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs.layout-bottom .sprocket-tabs-nav {
  border-top: 1px solid #ecf0f1;
  margin-top: 20px;
}
/* line 188, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs.layout-bottom li {
  border-right: 1px solid #ecf0f1 !important;
  margin-top: 0 !important;
}
/* line 193, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs .sprocket-tabs-nav {
  background: #f8f9fa;
  padding: 0 !important;
}
/* line 197, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs li {
  margin: 0;
}
/* line 199, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs li.active {
  margin: 0;
  color: #3d3d3d;
}
/* line 202, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs li.active span {
  background-color: transparent !important;
}
/* line 206, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-tabs li span.sprocket-tabs-inner {
  border: none !important;
  border-radius: 0;
  line-height: inherit;
  padding: 15px 20px;
}
/* line 215, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 216, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 217, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.white .sprocket-tabs .sprocket-tabs-nav {
  background: #fff;
}
/* line 224, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 225, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-header, .sprocket-mosaic .sprocket-mosaic-g-header {
  margin-bottom: 30px;
}
/* line 227, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 228, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-header ul li, .sprocket-mosaic .sprocket-mosaic-g-header ul li {
  border: 2px solid #ecf0f1;
  border-radius: 50px;
  background: #fff;
  text-transform: none;
  padding: 5px 20px;
  color: inherit;
  -webkit-transition: all 0.2s;
  -moz-transition: all 0.2s;
  transition: all 0.2s;
}
/* line 236, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-header ul li.active, .sprocket-mosaic .sprocket-mosaic-g-header ul li.active, .sprocket-mosaic .sprocket-mosaic-header ul li:hover, .sprocket-mosaic .sprocket-mosaic-g-header ul li:hover {
  border-color: #3d3d3d;
  background: #3d3d3d;
  color: #fff;
}
/* line 243, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
@media only all and (max-width: 47.938rem) {
  .sprocket-mosaic .sprocket-mosaic-header .sprocket-mosaic-filter, .sprocket-mosaic .sprocket-mosaic-g-header .sprocket-mosaic-filter, .sprocket-mosaic .sprocket-mosaic-header .sprocket-mosaic-g-filter, .sprocket-mosaic .sprocket-mosaic-g-header .sprocket-mosaic-g-filter {
    margin-bottom: 15px;
  }
}
/* line 247, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-header .sprocket-mosaic-filter li, .sprocket-mosaic .sprocket-mosaic-g-header .sprocket-mosaic-filter li, .sprocket-mosaic .sprocket-mosaic-header .sprocket-mosaic-g-filter li, .sprocket-mosaic .sprocket-mosaic-g-header .sprocket-mosaic-g-filter li {
  margin-right: 3px;
}
/* line 251, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
@media only all and (max-width: 47.938rem) {
  .sprocket-mosaic .sprocket-mosaic-header .sprocket-mosaic-order, .sprocket-mosaic .sprocket-mosaic-g-header .sprocket-mosaic-order, .sprocket-mosaic .sprocket-mosaic-header .sprocket-mosaic-g-order, .sprocket-mosaic .sprocket-mosaic-g-header .sprocket-mosaic-g-order {
    float: left;
  }
}
/* line 255, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-header .sprocket-mosaic-order li, .sprocket-mosaic .sprocket-mosaic-g-header .sprocket-mosaic-order li, .sprocket-mosaic .sprocket-mosaic-header .sprocket-mosaic-g-order li, .sprocket-mosaic .sprocket-mosaic-g-header .sprocket-mosaic-g-order li {
  margin-left: 3px;
}
/* line 260, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-container {
  margin: -15px;
}
/* line 263, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item {
  border-radius: 0;
  border: 1px solid #ecf0f1;
  background: #fff;
  margin: 15px;
}
/* line 268, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-padding {
  padding: 0;
}
/* line 270, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 271, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-padding .sprocket-mosaic-head .sprocket-mosaic-title {
  font-size: 1.15rem;
  margin: 0;
}
/* line 274, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-padding .sprocket-mosaic-head .sprocket-mosaic-title a {
  color: #252d37;
}
/* line 276, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-padding .sprocket-mosaic-head .sprocket-mosaic-title a:hover {
  color: #3d3d3d;
}
/* line 283, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 284, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-mosaic-image-container .sprocket-image-overlay {
  position: absolute;
  width: 100%;
  height: 100%;
  display: block;
  top: 0;
  background: rgba(0, 0, 0, 0.5);
  color: #fff;
  opacity: 0;
  -webkit-transition: opacity 0.3s;
  -moz-transition: opacity 0.3s;
  transition: opacity 0.3s;
}
/* line 294, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-mosaic-image-container .sprocket-image-overlay:before {
  font-size: 20px;
  height: 55px;
  width: 55px;
  border-radius: 50%;
  background: #3d3d3d;
  text-align: center;
  line-height: 55px;
  margin-left: -27.5px;
  margin-top: -27.5px;
  color: #fff;
  position: absolute;
  left: 50%;
  top: 50%;
  content: "\f0c1";
  font-family: FontAwesome;
}
/* line 312, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 313, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-mosaic-image-container:hover .sprocket-image-overlay {
  opacity: 1;
}
/* line 318, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-mosaic-content-wrapper {
  padding: 20px;
}
/* line 320, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-mosaic-content-wrapper .sprocket-mosaic-head {
  margin: 0;
  padding: 0;
}
/* line 324, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-mosaic-content-wrapper .sprocket-mosaic-text {
  margin: 15px 0 0;
}
/* line 328, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-readmore-tags {
  margin: 15px 0 0;
}
/* line 330, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-readmore-tags .sprocket-mosaic-tags {
  background: none;
  border-radius: 0;
  margin: 0;
  padding: 0;
  display: inline-block;
  float: right;
  font-style: normal;
}
/* line 338, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-readmore-tags .sprocket-mosaic-tags li {
  background: #f6f7f9;
}
/* line 342, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-readmore-tags .sprocket-readmore {
  display: inline-block;
}
/* line 344, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-item .sprocket-readmore-tags .sprocket-readmore:hover {
  color: #3d3d3d;
  text-decoration: underline;
}
/* line 351, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 352, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-g-item .sprocket-mosaic-g-effect {
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.5);
  -webkit-transition: opacity 0.3s;
  -moz-transition: opacity 0.3s;
  transition: opacity 0.3s;
}
/* line 358, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-g-item .sprocket-mosaic-g-content {
  text-align: center;
  padding: 20px;
}
/* line 361, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-g-item .sprocket-mosaic-g-content .sprocket-mosaic-g-title {
  font-size: 1.15rem;
  -webkit-transition: all 0.3s;
  -moz-transition: all 0.3s;
  transition: all 0.3s;
}
/* line 364, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-g-item .sprocket-mosaic-g-content .sprocket-mosaic-g-title a {
  color: #fff;
}
/* line 366, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-g-item .sprocket-mosaic-g-content .sprocket-mosaic-g-title a:hover {
  color: #3d3d3d;
}
/* line 371, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-g-item .sprocket-mosaic-g-content .sprocket-mosaic-g-text, .sprocket-mosaic .sprocket-mosaic-g-item .sprocket-mosaic-g-content .sprocket-mosaic-g-readon, .sprocket-mosaic .sprocket-mosaic-g-item .sprocket-mosaic-g-content .sprocket-mosaic-g-tags {
  display: none;
}
/* line 376, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-loadmore, .sprocket-mosaic .sprocket-mosaic-g-loadmore {
  background: #3d3d3d;
  color: #fff;
  border: none;
  padding: 10px 15px;
  margin-bottom: 0;
  margin-top: 30px;
  -webkit-transition: all 0.2s;
  -moz-transition: all 0.2s;
  transition: all 0.2s;
}
/* line 384, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-loadmore:hover, .sprocket-mosaic .sprocket-mosaic-g-loadmore:hover {
  background: #252d37;
  color: #fff;
}
/* line 388, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-loadmore .loadmore-info, .sprocket-mosaic .sprocket-mosaic-g-loadmore .loadmore-info {
  display: none;
}
/* line 391, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 392, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-loadmore .loadmore-all span, .sprocket-mosaic .sprocket-mosaic-g-loadmore .loadmore-all span {
  line-height: inherit;
}
/* line 397, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
/* line 398, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.sprocket-mosaic .sprocket-mosaic-g-loadmore span {
  font-size: 13px;
  text-transform: uppercase;
}
@media only all and (max-width: 30rem) {
  /* line 404, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
  /* line 405, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
  .sprocket-mosaic .sprocket-mosaic-g-columns-1 > li, .sprocket-mosaic .sprocket-mosaic-g-columns-2 > li, .sprocket-mosaic .sprocket-mosaic-g-columns-3 > li, .sprocket-mosaic .sprocket-mosaic-g-columns-4 > li, .sprocket-mosaic .sprocket-mosaic-g-columns-5 > li, .sprocket-mosaic .sprocket-mosaic-g-columns-6 > li {
    width: 100%;
  }
}
/* line 413, templates/it_medical/scss/medical-joomla/_roksprocket.scss */
.css-loader-wrapper {
  box-sizing: content-box;
}
/* line 1, templates/it_medical/scss/medical-joomla/_search.scss */
/* line 2, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-form-results {
  width: 500px;
  margin: 0 auto;
  text-align: center;
  padding: 50px;
  border: 1px solid #ecf0f1;
  margin-bottom: 70px;
  background: #f8f9fa;
}
@media only all and (max-width: 47.938rem) {
  .search .search-form-results {
    width: 100%;
  }
}
@media only all and (min-width: 48rem) and (max-width: 59.938rem) {
  .search .search-form-results {
    width: 100%;
  }
}
/* line 16, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-form-results .btn-toolbar {
  margin-top: 0;
}
/* line 18, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-form-results .btn-toolbar .btn-group {
  float: none;
  margin: 0;
}
/* line 21, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-form-results .btn-toolbar .btn-group input {
  width: 100%;
  margin: 0;
  border-right: none;
}
@media only all and (max-width: 30rem) {
  .search .search-form-results .btn-toolbar .btn-group input {
    width: 120px;
  }
}
/* line 29, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-form-results .btn-toolbar .btn-group .btn {
  padding: 0.58rem 1rem !important;
  border-radius: 0 0.1875rem 0.1875rem 0 !important;
}
/* line 32, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-form-results .btn-toolbar .btn-group .btn > span {
  vertical-align: middle;
  margin: 0;
}
/* line 39, templates/it_medical/scss/medical-joomla/_search.scss */
/* line 40, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-form-results .searchintro > p {
  margin-bottom: 0;
}
/* line 43, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-form-results .searchintro .badge {
  background: #3d3d3d;
  text-shadow: none;
}
/* line 49, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-add-options {
  padding: 50px;
  border: 1px solid #ecf0f1;
  margin: 0 auto 50px;
  width: 600px;
  background: #f8f9fa;
}
@media only all and (max-width: 47.938rem) {
  .search .search-add-options {
    width: 100%;
  }
}
@media only all and (min-width: 48rem) and (max-width: 59.938rem) {
  .search .search-add-options {
    width: 100%;
  }
}
@media only all and (min-width: 60rem) and (max-width: 74.938rem) {
  .search .search-add-options {
    width: 550px;
  }
}
/* line 64, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-add-options > fieldset {
  display: inline-block;
}
/* line 66, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-add-options > fieldset:first-child {
  margin-right: 50px;
}
@media only all and (max-width: 47.938rem) {
  .search .search-add-options > fieldset:first-child {
    margin-bottom: 50px;
  }
}
@media only all and (min-width: 48rem) and (max-width: 59.938rem) {
  .search .search-add-options > fieldset:first-child {
    margin-bottom: 50px;
  }
}
/* line 77, templates/it_medical/scss/medical-joomla/_search.scss */
/* line 78, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-results .result-item {
  padding: 40px 0 40px 50px;
  border-top: 1px solid #ecf0f1;
  position: relative;
}
/* line 82, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-results .result-item .item-number {
  position: absolute;
  left: 0;
  border: 1px solid #ecf0f1;
  text-align: center;
  width: 30px;
  height: 30px;
  line-height: 30px;
  border-radius: 0.1875rem;
}
/* line 92, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-results .result-item .result-title {
  line-height: 30px;
}
/* line 94, templates/it_medical/scss/medical-joomla/_search.scss */
/* line 95, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-results .result-item .result-title h4 a {
  color: #252d37;
}
/* line 97, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-results .result-item .result-title h4 a:hover {
  color: #3d3d3d;
}
/* line 103, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-results .result-item dd {
  margin: 0;
}
/* line 106, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-results .result-item .search-item-info {
  margin-top: 20px;
}
/* line 108, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-results .result-item .search-item-info dd {
  display: inline-block;
  margin-right: 20px;
}
/* line 111, templates/it_medical/scss/medical-joomla/_search.scss */
.search .search-results .result-item .search-item-info dd i {
  margin-right: 7px;
}
@media only all and (max-width: 47.938rem) {
  /* line 2, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar-fixed-top, .navbar-fixed-bottom, .navbar-static-top {
    margin-right: -20px;
    margin-left: -20px;
  }
  /* line 8, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .container-fluid {
    padding: 0;
  }
  /* line 11, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .dl-horizontal dt {
    float: none;
    width: auto;
    clear: none;
    text-align: left;
  }
  /* line 17, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .dl-horizontal dd {
    margin-left: 0;
  }
  /* line 20, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid {
    width: 100%;
  }
  /* line 23, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row, .thumbnails {
    margin-left: 0;
  }
  /* line 27, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .thumbnails > li {
    float: none;
    margin-left: 0;
  }
  /* line 32, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .manager.thumbnails > li {
    float: left;
    margin-left: 20px;
  }
  /* line 37, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  [class*="span"], .uneditable-input[class*="span"], .row-fluid [class*="span"] {
    display: block;
    float: none;
    width: 100%;
    margin-left: 0;
    box-sizing: border-box;
  }
  /* line 46, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span12, .row-fluid .span12 {
    width: 100%;
    box-sizing: border-box;
  }
  /* line 51, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid [class*="offset"]:first-child {
    margin-left: 0;
  }
  /* line 54, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .input-large, .input-xlarge, .input-xxlarge, input[class*="span"], select[class*="span"], textarea[class*="span"], .uneditable-input {
    display: block;
    width: 100%;
    min-height: 30px;
    box-sizing: border-box;
  }
  /* line 66, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .input-prepend input, .input-append input, .input-prepend input[class*="span"], .input-append input[class*="span"] {
    display: inline-block;
    width: auto;
  }
  /* line 73, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .controls-row [class*="span"] + [class*="span"] {
    margin-left: 0;
  }
}
@media only all and (max-width: 30rem) {
  /* line 79, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse {
    -webkit-transform: translate3d(0, 0, 0);
  }
  /* line 82, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .page-header h1 small {
    display: block;
    line-height: 20px;
  }
  /* line 86, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .form-horizontal .control-label {
    float: none;
    width: auto;
    padding-top: 0;
    text-align: left;
  }
  /* line 92, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .form-horizontal .controls {
    margin-left: 0;
  }
  /* line 95, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .form-horizontal .control-list {
    padding-top: 0;
  }
  /* line 98, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .form-horizontal .form-actions {
    padding-right: 10px;
    padding-left: 10px;
  }
  /* line 102, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .media .pull-left, .media .pull-right {
    display: block;
    float: none;
    margin-bottom: 10px;
  }
  /* line 108, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .media-object {
    margin-right: 0;
    margin-left: 0;
  }
  /* line 112, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .modal-header .close {
    padding: 10px;
    margin: -10px;
  }
}
@media only all and (min-width: 48rem) and (max-width: 59.938rem) {
  /* line 119, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row {
    margin-left: -20px;
  }
  /* line 122, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row:before, .row:after {
    display: table;
    line-height: 0;
    content: "";
  }
  /* line 128, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row:after {
    clear: both;
  }
  /* line 131, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  [class*="span"] {
    float: left;
    min-height: 1px;
    margin-left: 20px;
  }
  /* line 136, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span12 {
    width: 724px;
  }
  /* line 139, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span11 {
    width: 662px;
  }
  /* line 142, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span10 {
    width: 600px;
  }
  /* line 145, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span9 {
    width: 538px;
  }
  /* line 148, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span8 {
    width: 476px;
  }
  /* line 151, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span7 {
    width: 414px;
  }
  /* line 154, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span6 {
    width: 352px;
  }
  /* line 157, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span5 {
    width: 290px;
  }
  /* line 160, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span4 {
    width: 228px;
  }
  /* line 163, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span3 {
    width: 166px;
  }
  /* line 166, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span2 {
    width: 104px;
  }
  /* line 169, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .span1 {
    width: 42px;
  }
  /* line 172, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset12 {
    margin-left: 764px;
  }
  /* line 175, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset11 {
    margin-left: 702px;
  }
  /* line 178, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset10 {
    margin-left: 640px;
  }
  /* line 181, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset9 {
    margin-left: 578px;
  }
  /* line 184, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset8 {
    margin-left: 516px;
  }
  /* line 187, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset7 {
    margin-left: 454px;
  }
  /* line 190, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset6 {
    margin-left: 392px;
  }
  /* line 193, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset5 {
    margin-left: 330px;
  }
  /* line 196, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset4 {
    margin-left: 268px;
  }
  /* line 199, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset3 {
    margin-left: 206px;
  }
  /* line 202, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset2 {
    margin-left: 144px;
  }
  /* line 205, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .offset1 {
    margin-left: 82px;
  }
  /* line 208, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid {
    width: 100%;
  }
  /* line 211, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid:before, .row-fluid:after {
    display: table;
    line-height: 0;
    content: "";
  }
  /* line 217, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid:after {
    clear: both;
  }
  /* line 220, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid [class*="span"] {
    display: block;
    float: left;
    width: 100%;
    min-height: 30px;
    margin-left: 2.7624309392%;
    box-sizing: border-box;
  }
  /* line 228, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid [class*="span"]:first-child {
    margin-left: 0;
  }
  /* line 231, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .controls-row [class*="span"] + [class*="span"] {
    margin-left: 2.7624309392%;
  }
  /* line 234, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span12 {
    width: 100%;
  }
  /* line 237, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span11 {
    width: 91.4364640884%;
  }
  /* line 240, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span10 {
    width: 82.8729281768%;
  }
  /* line 243, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span9 {
    width: 74.3093922652%;
  }
  /* line 246, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span8 {
    width: 65.7458563536%;
  }
  /* line 249, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span7 {
    width: 57.182320442%;
  }
  /* line 252, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span6 {
    width: 48.6187845304%;
  }
  /* line 255, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span5 {
    width: 40.0552486188%;
  }
  /* line 258, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span4 {
    width: 31.4917127072%;
  }
  /* line 261, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span3 {
    width: 22.9281767956%;
  }
  /* line 264, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span2 {
    width: 14.364640884%;
  }
  /* line 267, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .span1 {
    width: 5.8011049724%;
  }
  /* line 270, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset12 {
    margin-left: 105.5248618785%;
  }
  /* line 273, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset12:first-child {
    margin-left: 102.7624309392%;
  }
  /* line 276, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset11 {
    margin-left: 96.9613259669%;
  }
  /* line 279, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset11:first-child {
    margin-left: 94.1988950276%;
  }
  /* line 282, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset10 {
    margin-left: 88.3977900552%;
  }
  /* line 285, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset10:first-child {
    margin-left: 85.635359116%;
  }
  /* line 288, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset9 {
    margin-left: 79.8342541436%;
  }
  /* line 291, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset9:first-child {
    margin-left: 77.0718232044%;
  }
  /* line 294, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset8 {
    margin-left: 71.270718232%;
  }
  /* line 297, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset8:first-child {
    margin-left: 68.5082872928%;
  }
  /* line 300, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset7 {
    margin-left: 62.7071823204%;
  }
  /* line 303, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset7:first-child {
    margin-left: 59.9447513812%;
  }
  /* line 306, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset6 {
    margin-left: 54.1436464088%;
  }
  /* line 309, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset6:first-child {
    margin-left: 51.3812154696%;
  }
  /* line 312, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset5 {
    margin-left: 45.5801104972%;
  }
  /* line 315, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset5:first-child {
    margin-left: 42.817679558%;
  }
  /* line 318, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset4 {
    margin-left: 37.0165745856%;
  }
  /* line 321, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset4:first-child {
    margin-left: 34.2541436464%;
  }
  /* line 324, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset3 {
    margin-left: 28.453038674%;
  }
  /* line 327, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset3:first-child {
    margin-left: 25.6906077348%;
  }
  /* line 330, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset2 {
    margin-left: 19.8895027624%;
  }
  /* line 333, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset2:first-child {
    margin-left: 17.1270718232%;
  }
  /* line 336, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset1 {
    margin-left: 11.3259668508%;
  }
  /* line 339, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .row-fluid .offset1:first-child {
    margin-left: 8.5635359116%;
  }
  /* line 342, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input, textarea, .uneditable-input {
    margin-left: 0;
  }
  /* line 347, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .controls-row [class*="span"] + [class*="span"] {
    margin-left: 20px;
  }
  /* line 350, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span12, textarea.span12, .uneditable-input.span12 {
    width: 710px;
  }
  /* line 355, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span11, textarea.span11, .uneditable-input.span11 {
    width: 648px;
  }
  /* line 360, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span10, textarea.span10, .uneditable-input.span10 {
    width: 586px;
  }
  /* line 365, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span9, textarea.span9, .uneditable-input.span9 {
    width: 524px;
  }
  /* line 370, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span8, textarea.span8, .uneditable-input.span8 {
    width: 462px;
  }
  /* line 375, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span7, textarea.span7, .uneditable-input.span7 {
    width: 400px;
  }
  /* line 380, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span6, textarea.span6, .uneditable-input.span6 {
    width: 338px;
  }
  /* line 385, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span5, textarea.span5, .uneditable-input.span5 {
    width: 276px;
  }
  /* line 390, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span4, textarea.span4, .uneditable-input.span4 {
    width: 214px;
  }
  /* line 395, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span3, textarea.span3, .uneditable-input.span3 {
    width: 152px;
  }
  /* line 400, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span2, textarea.span2, .uneditable-input.span2 {
    width: 90px;
  }
  /* line 405, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  input.span1, textarea.span1, .uneditable-input.span1 {
    width: 28px;
  }
}
@media only all and (max-width: 59.938rem) {
  /* line 413, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar-fixed-top, .navbar-fixed-bottom {
    position: static;
  }
  /* line 417, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar-fixed-top {
    margin-bottom: 20px;
  }
  /* line 420, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar-fixed-bottom {
    margin-top: 20px;
  }
  /* line 423, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar-fixed-top .navbar-inner, .navbar-fixed-bottom .navbar-inner {
    padding: 5px;
  }
  /* line 427, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar .container {
    width: auto;
    padding: 0;
  }
  /* line 431, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar .brand {
    padding-right: 10px;
    padding-left: 10px;
    margin: 0 0 0 -5px;
  }
  /* line 436, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse {
    clear: both;
  }
  /* line 439, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .nav {
    float: none;
    margin: 0 0 10px;
  }
  /* line 443, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .nav > li {
    float: none;
  }
  /* line 446, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .nav > li > a {
    margin-bottom: 2px;
  }
  /* line 449, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .nav > .divider-vertical {
    display: none;
  }
  /* line 452, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .nav .nav-header {
    color: #777;
    text-shadow: none;
  }
  /* line 456, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .nav > li > a, .nav-collapse .dropdown-menu a {
    padding: 9px 15px;
    font-weight: bold;
    color: #777;
    border-radius: 0.1875rem;
  }
  /* line 463, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .btn {
    padding: 4px 10px 4px;
    font-weight: normal;
    border-radius: 0.1875rem;
  }
  /* line 468, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .dropdown-menu li + li a {
    margin-bottom: 2px;
  }
  /* line 471, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .nav > li > a:hover, .nav-collapse .nav > li > a:focus, .nav-collapse .dropdown-menu a:hover, .nav-collapse .dropdown-menu a:focus {
    background-color: #f2f2f2;
  }
  /* line 477, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar-inverse .nav-collapse .nav > li > a, .navbar-inverse .nav-collapse .dropdown-menu a {
    color: #999;
  }
  /* line 481, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar-inverse .nav-collapse .nav > li > a:hover, .navbar-inverse .nav-collapse .nav > li > a:focus, .navbar-inverse .nav-collapse .dropdown-menu a:hover, .navbar-inverse .nav-collapse .dropdown-menu a:focus {
    background-color: #111;
  }
  /* line 487, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse.in .btn-group {
    padding: 0;
    margin-top: 5px;
  }
  /* line 491, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .dropdown-menu {
    position: static;
    top: auto;
    left: auto;
    display: none;
    float: none;
    max-width: none;
    padding: 0;
    margin: 0 15px;
    background-color: transparent;
    border: none;
    border-radius: 0;
    box-shadow: none;
  }
  /* line 505, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .open > .dropdown-menu {
    display: block;
  }
  /* line 508, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .dropdown-menu:before, .nav-collapse .dropdown-menu:after {
    display: none;
  }
  /* line 512, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .dropdown-menu .divider {
    display: none;
  }
  /* line 515, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .nav > li > .dropdown-menu:before, .nav-collapse .nav > li > .dropdown-menu:after {
    display: none;
  }
  /* line 519, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse .navbar-form, .nav-collapse .navbar-search {
    float: none;
    padding: 10px 15px;
    margin: 10px 0;
    border-top: 1px solid #f2f2f2;
    border-bottom: 1px solid #f2f2f2;
    box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 0 rgba(255, 255, 255, 0.1);
  }
  /* line 528, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar-inverse .nav-collapse .navbar-form, .navbar-inverse .nav-collapse .navbar-search {
    border-top-color: #111;
    border-bottom-color: #111;
  }
  /* line 533, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar .nav-collapse .nav.pull-right {
    float: none;
    margin-left: 0;
  }
  /* line 537, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse, .nav-collapse.collapse {
    height: 0;
    overflow: hidden;
  }
  /* line 542, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar .btn-navbar {
    display: block;
  }
  /* line 545, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .navbar-static .navbar-inner {
    padding-right: 10px;
    padding-left: 10px;
  }
}
@media only all and (min-width: 60rem) {
  /* line 552, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_bootstrap.scss */
  .nav-collapse.collapse {
    height: auto !important;
    overflow: visible !important;
  }
}
@media only all and (max-width: 47.938rem) {
  /* line 2, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_forms.scss */
  /* line 3, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_forms.scss */
  .form-horizontal .control-label {
    display: block;
    float: none;
    text-align: left;
  }
  /* line 9, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_forms.scss */
  .form-horizontal .controls {
    margin: 0;
  }
  /* line 14, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_forms.scss */
  [dir="rtl"] .form-horizontal .control-label {
    text-align: right;
  }
}
@media only all and (max-width: 47.938rem) {
  /* line 2, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_utilities.scss */
  div.modal {
    position: fixed;
    top: 20px;
    right: 20px;
    left: 20px;
    width: auto;
    margin: 0;
  }
  /* line 10, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_utilities.scss */
  div.modal.fade {
    top: -100px;
  }
  /* line 13, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_utilities.scss */
  div.modal.fade.in {
    top: 20px;
  }
}
@media only all and (max-width: 30rem) {
  /* line 19, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_utilities.scss */
  div.modal {
    top: 10px;
    right: 10px;
    left: 10px;
  }
}
@media only all and (max-width: 47.938rem) {
  /* line 27, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_utilities.scss */
  /* line 28, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_utilities.scss */
  .pull-right.item-image {
    margin-left: 0;
  }
  /* line 33, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_utilities.scss */
  /* line 34, media/gantry5/engines/nucleus/scss/joomla/theme/breakpoints/_utilities.scss */
  .pull-left.item-image {
    margin-right: 0;
  }
}
/*# sourceMappingURL=medical-joomla_16.css.map */
